-- Portfolio v2 migration. Safe to re-run (idempotent).
-- Run in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.

-- 1) activity_logs (exists from v1; make sure every column v2 uses is there) -------------------
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);
alter table public.activity_logs add column if not exists external_id   text;
alter table public.activity_logs add column if not exists platform      text;
alter table public.activity_logs add column if not exists activity_date date;
alter table public.activity_logs add column if not exists intensity     integer default 1;
alter table public.activity_logs add column if not exists title         text;
alter table public.activity_logs add column if not exists url           text;
alter table public.activity_logs add column if not exists type          text;
alter table public.activity_logs add column if not exists description   text;
alter table public.activity_logs add column if not exists metadata      jsonb;
-- needed by upsert(onConflict: external_id); NULLs stay distinct so legacy rows are untouched
create unique index if not exists activity_logs_external_id_key on public.activity_logs (external_id);
create index if not exists activity_logs_date_idx on public.activity_logs (activity_date desc);

-- 2) source_cache: last-good JSON per source ---------------------------------------------------
create table if not exists public.source_cache (
  source     text primary key,
  payload    jsonb not null,
  fetched_at timestamptz not null default now()
);

-- 3) social_posts: LinkedIn / X posts added from /admin ----------------------------------------
create table if not exists public.social_posts (
  id          uuid primary key default gen_random_uuid(),
  platform    text not null check (platform in ('linkedin', 'x')),
  url         text not null unique,
  external_id text,
  embed_url   text,
  text        text,
  author      text,
  note        text,
  posted_at   timestamptz,
  pinned      boolean not null default false,
  hidden      boolean not null default false,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists social_posts_order_idx on public.social_posts (pinned desc, sort_order, posted_at desc);

-- 4) resume_versions ---------------------------------------------------------------------------
create table if not exists public.resume_versions (
  id          uuid primary key default gen_random_uuid(),
  url         text not null,
  path        text,
  filename    text,
  uploaded_at timestamptz not null default now(),
  is_current  boolean not null default false
);
-- at most one current resume
create unique index if not exists resume_versions_one_current on public.resume_versions (is_current) where is_current;

-- 5) site_settings (key -> json) ---------------------------------------------------------------
create table if not exists public.site_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);
insert into public.site_settings (key, value)
values ('status', '{"currently": "", "openToWork": true}'::jsonb)
on conflict (key) do nothing;

-- 6) Row level security: public read, writes only via service role (which bypasses RLS) --------
alter table public.activity_logs   enable row level security;
alter table public.source_cache    enable row level security;
alter table public.social_posts    enable row level security;
alter table public.resume_versions enable row level security;
alter table public.site_settings   enable row level security;

drop policy if exists "public read" on public.activity_logs;
create policy "public read" on public.activity_logs   for select using (true);
drop policy if exists "public read" on public.source_cache;
create policy "public read" on public.source_cache    for select using (true);
drop policy if exists "public read visible" on public.social_posts;
create policy "public read visible" on public.social_posts for select using (not hidden);
drop policy if exists "public read" on public.resume_versions;
create policy "public read" on public.resume_versions for select using (true);
drop policy if exists "public read" on public.site_settings;
create policy "public read" on public.site_settings   for select using (true);

-- 7) Storage bucket for resumes (public read; uploads happen server-side with the service role) -
insert into storage.buckets (id, name, public)
values ('resume', 'resume', true)
on conflict (id) do update set public = true;
